# This file created by conda-build 26.1.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Feb 17 17:40:24 2026
# ------------------------------------------------

package:
  name: bzip2
  version: 1.0.8
source:
  url: https://gitlab.com/bzip2/bzip2/-/archive/bzip2-1.0.8/bzip2-bzip2-1.0.8.tar.gz
  sha256: db106b740252669664fd8f3a1c69fe7f689d5cd4b132f82ba82b9afba27627df
  patches:
    - patches/0001-cross.patch
    - patches/0002-Windows-Make-library-name-lowercase.patch
    - patches/0003-Windows-Add-dyn-lib-build-rename-libbz2_static.patch
build:
  number: '9'
  run_exports:
    - bzip2 >=1.0.8,<2.0a0
  string: hd037594_9
requirements:
  build:
    - ca-certificates 2026.1.4 hbd8a1cb_0
    - cctools_impl_osx-64 1030.6.3 llvm19_1_h7d82c7c_4
    - cctools_impl_osx-arm64 1030.6.3 llvm19_1_h322ffc5_4
    - cctools_osx-arm64 1030.6.3 llvm19_1_h6cc4725_4
    - clang 19.1.7 default_h1323312_7
    - clang-19 19.1.7 default_hd70426c_7
    - clang_impl_osx-64 19.1.7 default_ha1a018a_7
    - clang_impl_osx-arm64 19.1.7 h4c5f930_31
    - clang_osx-arm64 19.1.7 h877a2d5_31
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - ld64 956.6 llvm19_1_hc3792c1_4
    - ld64_osx-64 956.6 llvm19_1_hcae3351_4
    - ld64_osx-arm64 956.6 llvm19_1_h46d26d2_4
    - libclang-cpp19.1 19.1.7 default_hd70426c_7
    - libcxx 21.1.8 h4fb565c_2
    - libiconv 1.18 h57a12c2_2
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.2 h11316ed_0
    - libsigtool 0.1.3 hc0f2934_0
    - libxml2 2.15.1 h745d5cb_1
    - libxml2-16 2.15.1 hd57b93d_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-openmp 21.1.8 h472b3d1_0
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - macosx_deployment_target_osx-arm64 11.0 h214bdd9_6
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.6.1 hb6871ef_1
    - sdkroot_env_osx-arm64 26.0 ha3f98da_6
    - sigtool-codesign 0.1.3 hc0f2934_0
    - tapi 1600.0.11.8 h8d8e812_0
    - zstd 1.5.7 h3eecb57_6
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - bzip2 --help
    - test -f ${PREFIX}/bin/bunzip2
    - test -f ${PREFIX}/bin/bzcat
    - test -f ${PREFIX}/bin/bzcmp
    - test -f ${PREFIX}/bin/bzdiff
    - test -f ${PREFIX}/bin/bzegrep
    - test -f ${PREFIX}/bin/bzfgrep
    - test -f ${PREFIX}/bin/bzgrep
    - test -f ${PREFIX}/bin/bzip2recover
    - test -f ${PREFIX}/bin/bzip2
    - test -f ${PREFIX}/bin/bzless
    - test -f ${PREFIX}/bin/bzmore
    - test -f ${PREFIX}/include/bzlib.h
    - test -f ${PREFIX}/lib/libbz2.a
    - test -f ${PREFIX}/lib/libbz2.dylib
about:
  home: https://gitlab.com/bzip2/bzip2
  license_family: BSD
  license_file: LICENSE
  license: bzip2-1.0.6
  summary: high-quality data compressor
  description: 'Bzip2 is a freely available high-quality data compressor. It typically

    compresses files to within 10% to 15% of the best available techniques,

    whilst being around twice as fast at compression and six times faster

    at decompression.

    '
  dev_url: https://gitlab.com/bzip2/bzip2
extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mbargull
    - msarahan
    - pelson
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260217.2.1
  remote_url: https://github.com/conda-forge/bzip2-feedstock
  sha: 0e3dc2c6bf25975daa14ec1c2c9e4f282787daf1
