# This file created by conda-build 25.11.1
# ------------------------------------------------

package:
  name: liblzma
  version: 5.8.2
source:
  url: https://github.com/tukaani-project/xz/releases/download/v5.8.2/xz-5.8.2.tar.gz
  sha256: ce09c50a5962786b83e5da389c90dd2c15ecd0980a258dd01f70f9e7ce58a8f1
build:
  run_exports:
    - liblzma >=5.8.2,<6.0a0
  number: 0
  string: h8088a28_0
requirements:
  build:
    - clang_bootstrap_osx-arm64 19.1.7 h4c5f930_30
    - macosx_deployment_target_osx-arm64 11.0 h6553868_5
    - make 4.4.1 h00291cd_2
  run_constrained:
    - xz 5.8.2.*
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - test ! -f ${PREFIX}/lib/liblzma.a
    - test ! -f ${PREFIX}/lib/liblzma${SHLIB_EXT}
    - test -f ${PREFIX}/lib/liblzma.*.dylib
about:
  home: http://tukaani.org/xz/
  dev_url: http://git.tukaani.org/
  summary: a compression library with an API similar to that of zlib
  license: 0BSD
  license_file:
    - COPYING
    - COPYING.0BSD
extra:
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
    - xhochy
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260118.2.1
  remote_url: https://github.com/conda-forge/xz-feedstock
  sha: 552bba367d56872022f0ca368a3fa92472484a8c
