CONDA_BUILD_SYSROOT: /opt/conda-sdks/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
build_platform: osx-64
c_stdlib: macosx_deployment_target
c_stdlib_version: '11.0'
channel_sources: conda-forge
channel_targets: conda-forge main
cxx_compiler: clangxx
cxx_compiler_version: '19'
fmt: '12.1'
libmamba: 2.5.0 h7950639_0
libmamba_spdlog: 2.5.0 h85b9800_0
openssl: '3.5'
pybind11: 3
pybind11_abi: 11
python: 3.13.* *_cp313
spdlog: '1.17'
target_platform: osx-arm64
zstd: '1.5'
