# This file created by conda-build 25.11.1
# ------------------------------------------------

package:
  name: libmpdec
  version: 4.0.0
source:
  url: https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-4.0.0.tar.gz
  sha256: 942445c3245b22730fd41a67a7c5c231d11cb1b9936b9c0f76334fb7d0b4468c
  patches:
    - fix-dll-name.diff
    - fix-win-arm64-config.diff
build:
  number: '1'
  noarch: false
  noarch_python: false
  python_version_independent: false
  string: h84a0fba_1
requirements:
  build:
    - ca-certificates 2026.1.4 hbd8a1cb_0
    - cctools_impl_osx-64 1030.6.3 llvm19_1_h7d82c7c_4
    - cctools_impl_osx-arm64 1030.6.3 llvm19_1_h322ffc5_4
    - cctools_osx-arm64 1030.6.3 llvm19_1_h6cc4725_4
    - clang 19.1.7 default_h1323312_7
    - clang-19 19.1.7 default_hd70426c_7
    - clang_impl_osx-64 19.1.7 default_ha1a018a_7
    - clang_impl_osx-arm64 19.1.7 h4c5f930_30
    - clang_osx-arm64 19.1.7 h877a2d5_30
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - ld64 956.6 llvm19_1_hc3792c1_4
    - ld64_osx-64 956.6 llvm19_1_hcae3351_4
    - ld64_osx-arm64 956.6 llvm19_1_h46d26d2_4
    - libclang-cpp19.1 19.1.7 default_hd70426c_7
    - libcxx 21.1.8 h3d58e20_0
    - libiconv 1.18 h57a12c2_2
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.2 h11316ed_0
    - libsigtool 0.1.3 hc0f2934_0
    - libxml2 2.15.1 h745d5cb_1
    - libxml2-16 2.15.1 hd57b93d_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-openmp 21.1.8 h472b3d1_0
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - macosx_deployment_target_osx-arm64 11.0 h214bdd9_6
    - ncurses 6.5 h0622a9a_3
    - openssl 3.6.0 h230baf5_0
    - sdkroot_env_osx-arm64 26.0 ha3f98da_6
    - sigtool-codesign 0.1.3 hc0f2934_0
    - tapi 1600.0.11.8 h8d8e812_0
    - zstd 1.5.7 h3eecb57_6
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - test -f ${PREFIX}/lib/libmpdec.4.dylib
about:
  home: https://www.bytereef.org/mpdecimal/index.html
  summary: A package for correctly-rounded arbitrary precision decimal floating point
    arithmetic
  license: BSD-2-Clause
  license_file: COPYRIGHT.txt
extra:
  recipe-maintainers:
    - isuruf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260126.4.1
  remote_url: https://github.com/conda-forge/mpdecimal-feedstock
  sha: fc3e04b6c42fdd6fefe944e7fae9865240838c56
