# This file created by conda-build 25.11.1
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Wed Jan  7 10:22:23 2026
# ------------------------------------------------

package:
  name: spdlog
  version: 1.17.0
source:
  url: https://github.com/gabime/spdlog/archive/v1.17.0.tar.gz
  sha256: d8862955c6d74e5846b3f580b1605d2428b11d97a410d86e2fb13e857cd3a744
  patches:
    - patches/fix.patch
build:
  number: '1'
  run_exports:
    - spdlog >=1.17.0,<1.18.0a0
  string: ha0f8610_1
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - c-ares 1.34.6 hb5e19a0_0
    - ca-certificates 2026.1.4 hbd8a1cb_0
    - cctools_impl_osx-64 1030.6.3 llvm19_1_h3b512aa_3
    - cctools_impl_osx-arm64 1030.6.3 llvm19_1_h5cc7f4e_3
    - cctools_osx-64 1030.6.3 llvm19_1_h8f0d4bb_3
    - cctools_osx-arm64 1030.6.3 llvm19_1_h6cc4725_3
    - clang 19.1.7 default_h1323312_5
    - clang-19 19.1.7 default_hc369343_5
    - clang_impl_osx-64 19.1.7 hc73cdc9_28
    - clang_impl_osx-arm64 19.1.7 h4c5f930_28
    - clang_osx-64 19.1.7 h7e5c614_28
    - clang_osx-arm64 19.1.7 h877a2d5_28
    - clangxx 19.1.7 default_h1c12a56_5
    - clangxx_impl_osx-64 19.1.7 hb295874_28
    - clangxx_impl_osx-arm64 19.1.7 ha2d6da0_28
    - clangxx_osx-arm64 19.1.7 h877a2d5_28
    - cmake 4.2.1 h29fc008_0
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - krb5 1.21.3 h37d8d59_0
    - ld64_osx-64 956.6 llvm19_1_h466f870_3
    - ld64_osx-arm64 956.6 llvm19_1_hcfa1dea_3
    - libclang-cpp19.1 19.1.7 default_hc369343_5
    - libcurl 8.17.0 h7dd4100_1
    - libcxx 21.1.8 h3d58e20_0
    - libcxx-devel 19.1.7 h7c275be_2
    - libcxx-headers 19.1.7 h707e725_2
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.7.3 heffb93a_0
    - libiconv 1.18 h57a12c2_2
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.1 hd471939_2
    - libnghttp2 1.67.0 h3338091_0
    - libsigtool 0.1.3 hc0f2934_0
    - libssh2 1.11.1 hed3591d_0
    - libuv 1.51.0 h58003a5_1
    - libxml2 2.15.1 h745d5cb_1
    - libxml2-16 2.15.1 hd57b93d_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - macosx_deployment_target_osx-arm64 11.0 h6553868_5
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.6.0 h230baf5_0
    - rhash 1.4.6 h6e16a3a_1
    - sdkroot_env_osx-64 26.0 hda3c137_5
    - sdkroot_env_osx-arm64 26.0 hc6f8731_5
    - sigtool-codesign 0.1.3 hc0f2934_0
    - tapi 1600.0.11.8 h8d8e812_0
    - zstd 1.5.7 h3eecb57_6
  host:
    - fmt 12.1.0 h403dcb5_0
    - libcxx 21.1.8 hf598326_0
  run:
    - __osx >=11.0
    - fmt >=12.1.0,<12.2.0a0
    - libcxx >=19
test:
  commands:
    - test -e $PREFIX/include/spdlog/spdlog.h
about:
  home: https://github.com/gabime/spdlog
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Super fast C++ logging library.
  description: 'spdlog is a header only library for Super fast C++ logging

    to be used with a C++11 compiler.

    '
extra:
  recipe-maintainers:
    - bluescarni
    - druvus
    - jjerphan
    - rongou
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260107.5.1
  remote_url: https://github.com/conda-forge/spdlog-feedstock
  sha: 6b4f979f949b9bd7dda7c9bce17fefb18db74d8f
