# This file created by conda-build 26.1.0
# ------------------------------------------------

package:
  name: libabseil
  version: '20260107.1'
source:
  url: https://github.com/abseil/abseil-cpp/archive/refs/tags/20260107.1.tar.gz
  sha256: 4314e2a7cbac89cac25a2f2322870f343d81579756ceff7f431803c2c9090195
  patches:
    - patches/0001-default-dll-import-for-windows.patch
    - patches/0002-don-t-use-C-20-stdlib-features-which-change-ABI-comp.patch
    - patches/0003-Don-t-try-to-compile-to-multiple-OSX-arches.patch
build:
  string: cxx17_h2062a1b_0
  run_exports:
    - libabseil =*=cxx17*
    - libabseil >=20260107.1,<20260108.0a0
  number: 0
requirements:
  build:
    - bzip2 1.0.8 h500dc9f_8
    - c-ares 1.34.6 hb5e19a0_0
    - ca-certificates 2026.1.4 hbd8a1cb_0
    - cctools_impl_osx-64 1030.6.3 llvm19_1_h7d82c7c_4
    - cctools_impl_osx-arm64 1030.6.3 llvm19_1_h322ffc5_4
    - cctools_osx-arm64 1030.6.3 llvm19_1_h6cc4725_4
    - clang 19.1.7 default_h1323312_7
    - clang-19 19.1.7 default_hd70426c_7
    - clang_impl_osx-64 19.1.7 default_ha1a018a_7
    - clang_impl_osx-arm64 19.1.7 h4c5f930_31
    - clang_osx-arm64 19.1.7 h877a2d5_31
    - clangxx 19.1.7 default_h9089c59_7
    - clangxx_impl_osx-64 19.1.7 default_ha1a018a_7
    - clangxx_impl_osx-arm64 19.1.7 ha2d6da0_31
    - clangxx_osx-arm64 19.1.7 h877a2d5_31
    - cmake 4.2.3 h965d0ab_0
    - compiler-rt 19.1.7 he914875_1
    - compiler-rt_osx-64 19.1.7 h138dee1_1
    - krb5 1.21.3 h37d8d59_0
    - ld64 956.6 llvm19_1_hc3792c1_4
    - ld64_osx-64 956.6 llvm19_1_hcae3351_4
    - ld64_osx-arm64 956.6 llvm19_1_h46d26d2_4
    - libclang-cpp19.1 19.1.7 default_hd70426c_7
    - libcurl 8.18.0 h9348e2b_0
    - libcxx 21.1.8 h4fb565c_2
    - libcxx-devel 19.1.7 h7c275be_2
    - libcxx-headers 19.1.7 h707e725_2
    - libedit 3.1.20250104 pl5321ha958ccf_0
    - libev 4.33 h10d778d_2
    - libexpat 2.7.3 heffb93a_0
    - libiconv 1.18 h57a12c2_2
    - libllvm19 19.1.7 h56e7563_2
    - liblzma 5.8.2 h11316ed_0
    - libnghttp2 1.67.0 h3338091_0
    - libsigtool 0.1.3 hc0f2934_0
    - libssh2 1.11.1 hed3591d_0
    - libuv 1.51.0 h58003a5_1
    - libxml2 2.15.1 h745d5cb_1
    - libxml2-16 2.15.1 hd57b93d_1
    - libzlib 1.3.1 hd23fc13_2
    - llvm-openmp 21.1.8 h472b3d1_0
    - llvm-tools 19.1.7 hb0207f0_2
    - llvm-tools-19 19.1.7 h879f4bc_2
    - macosx_deployment_target_osx-arm64 11.0 h214bdd9_6
    - ncurses 6.5 h0622a9a_3
    - ninja 1.13.2 hfc0b2d5_0
    - openssl 3.6.1 hb6871ef_1
    - rhash 1.4.6 h6e16a3a_1
    - sdkroot_env_osx-arm64 26.0 ha3f98da_6
    - sigtool-codesign 0.1.3 hc0f2934_0
    - tapi 1600.0.11.8 h8d8e812_0
    - zstd 1.5.7 h3eecb57_6
  run_constrained:
    - abseil-cpp =20260107.1
    - libabseil-static =20260107.1=cxx17*
  host:
    - libcxx 21.1.8 h55c6f16_2
  run:
    - __osx >=11.0
    - libcxx >=19
test:
  requires:
    - clangxx_osx-arm64 19.*
    - cmake
    - macosx_deployment_target_osx-arm64 11.0.*
    - ninja
    - pkg-config
  files:
    - cmake_test/
  commands:
    - test -f $PREFIX/lib/libabsl_decode_rust_punycode${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_decode_rust_punycode.a
    - pkg-config --print-errors --exact-version "20260107" absl_decode_rust_punycode
    - test -f $PREFIX/lib/libabsl_demangle_rust${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_demangle_rust.a
    - pkg-config --print-errors --exact-version "20260107" absl_demangle_rust
    - test -f $PREFIX/lib/libabsl_flags_commandlineflag${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_flags_commandlineflag.a
    - pkg-config --print-errors --exact-version "20260107" absl_flags_commandlineflag
    - test -f $PREFIX/lib/libabsl_flags_config${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_flags_config.a
    - pkg-config --print-errors --exact-version "20260107" absl_flags_config
    - test -f $PREFIX/lib/libabsl_flags_marshalling${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_flags_marshalling.a
    - pkg-config --print-errors --exact-version "20260107" absl_flags_marshalling
    - test -f $PREFIX/lib/libabsl_flags_parse${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_flags_parse.a
    - pkg-config --print-errors --exact-version "20260107" absl_flags_parse
    - test -f $PREFIX/lib/libabsl_flags_private_handle_accessor${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_flags_private_handle_accessor.a
    - pkg-config --print-errors --exact-version "20260107" absl_flags_private_handle_accessor
    - test -f $PREFIX/lib/libabsl_flags_program_name${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_flags_program_name.a
    - pkg-config --print-errors --exact-version "20260107" absl_flags_program_name
    - test -f $PREFIX/lib/libabsl_flags_reflection${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_flags_reflection.a
    - pkg-config --print-errors --exact-version "20260107" absl_flags_reflection
    - test -f $PREFIX/lib/libabsl_flags_usage${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_flags_usage.a
    - pkg-config --print-errors --exact-version "20260107" absl_flags_usage
    - test -f $PREFIX/lib/libabsl_hashtable_profiler${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_hashtable_profiler.a
    - pkg-config --print-errors --exact-version "20260107" absl_hashtable_profiler
    - test -f $PREFIX/lib/libabsl_log_flags${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_log_flags.a
    - pkg-config --print-errors --exact-version "20260107" absl_log_flags
    - test -f $PREFIX/lib/libabsl_poison${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_poison.a
    - pkg-config --print-errors --exact-version "20260107" absl_poison
    - test -f $PREFIX/lib/libabsl_profile_builder${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_profile_builder.a
    - pkg-config --print-errors --exact-version "20260107" absl_profile_builder
    - test -f $PREFIX/lib/libabsl_base${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_base.a
    - pkg-config --print-errors --exact-version "20260107" absl_base
    - test -f $PREFIX/lib/libabsl_civil_time${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_civil_time.a
    - pkg-config --print-errors --exact-version "20260107" absl_civil_time
    - test -f $PREFIX/lib/libabsl_crc_cord_state${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_crc_cord_state.a
    - pkg-config --print-errors --exact-version "20260107" absl_crc_cord_state
    - test -f $PREFIX/lib/libabsl_crc_cpu_detect${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_crc_cpu_detect.a
    - pkg-config --print-errors --exact-version "20260107" absl_crc_cpu_detect
    - test -f $PREFIX/lib/libabsl_crc32c${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_crc32c.a
    - pkg-config --print-errors --exact-version "20260107" absl_crc32c
    - test -f $PREFIX/lib/libabsl_cord${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_cord.a
    - pkg-config --print-errors --exact-version "20260107" absl_cord
    - test -f $PREFIX/lib/libabsl_cordz_functions${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_cordz_functions.a
    - pkg-config --print-errors --exact-version "20260107" absl_cordz_functions
    - test -f $PREFIX/lib/libabsl_cordz_handle${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_cordz_handle.a
    - pkg-config --print-errors --exact-version "20260107" absl_cordz_handle
    - test -f $PREFIX/lib/libabsl_cordz_info${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_cordz_info.a
    - pkg-config --print-errors --exact-version "20260107" absl_cordz_info
    - test -f $PREFIX/lib/libabsl_cordz_sample_token${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_cordz_sample_token.a
    - pkg-config --print-errors --exact-version "20260107" absl_cordz_sample_token
    - test -f $PREFIX/lib/libabsl_die_if_null${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_die_if_null.a
    - pkg-config --print-errors --exact-version "20260107" absl_die_if_null
    - test -f $PREFIX/lib/libabsl_examine_stack${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_examine_stack.a
    - pkg-config --print-errors --exact-version "20260107" absl_examine_stack
    - test -f $PREFIX/lib/libabsl_exponential_biased${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_exponential_biased.a
    - pkg-config --print-errors --exact-version "20260107" absl_exponential_biased
    - test -f $PREFIX/lib/libabsl_failure_signal_handler${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_failure_signal_handler.a
    - pkg-config --print-errors --exact-version "20260107" absl_failure_signal_handler
    - test -f $PREFIX/lib/libabsl_hash${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_hash.a
    - pkg-config --print-errors --exact-version "20260107" absl_hash
    - test -f $PREFIX/lib/libabsl_hashtablez_sampler${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_hashtablez_sampler.a
    - pkg-config --print-errors --exact-version "20260107" absl_hashtablez_sampler
    - test -f $PREFIX/lib/libabsl_int128${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_int128.a
    - pkg-config --print-errors --exact-version "20260107" absl_int128
    - test -f $PREFIX/lib/libabsl_log_severity${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_log_severity.a
    - pkg-config --print-errors --exact-version "20260107" absl_log_severity
    - test -f $PREFIX/lib/libabsl_periodic_sampler${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_periodic_sampler.a
    - pkg-config --print-errors --exact-version "20260107" absl_periodic_sampler
    - test -f $PREFIX/lib/libabsl_random_distributions${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_random_distributions.a
    - pkg-config --print-errors --exact-version "20260107" absl_random_distributions
    - test -f $PREFIX/lib/libabsl_random_seed_gen_exception${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_random_seed_gen_exception.a
    - pkg-config --print-errors --exact-version "20260107" absl_random_seed_gen_exception
    - test -f $PREFIX/lib/libabsl_random_seed_sequences${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_random_seed_sequences.a
    - pkg-config --print-errors --exact-version "20260107" absl_random_seed_sequences
    - test -f $PREFIX/lib/libabsl_raw_hash_set${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_raw_hash_set.a
    - pkg-config --print-errors --exact-version "20260107" absl_raw_hash_set
    - test -f $PREFIX/lib/libabsl_scoped_set_env${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_scoped_set_env.a
    - pkg-config --print-errors --exact-version "20260107" absl_scoped_set_env
    - test -f $PREFIX/lib/libabsl_spinlock_wait${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_spinlock_wait.a
    - pkg-config --print-errors --exact-version "20260107" absl_spinlock_wait
    - test -f $PREFIX/lib/libabsl_stacktrace${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_stacktrace.a
    - pkg-config --print-errors --exact-version "20260107" absl_stacktrace
    - test -f $PREFIX/lib/libabsl_status${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_status.a
    - pkg-config --print-errors --exact-version "20260107" absl_status
    - test -f $PREFIX/lib/libabsl_statusor${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_statusor.a
    - pkg-config --print-errors --exact-version "20260107" absl_statusor
    - test -f $PREFIX/lib/libabsl_strerror${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_strerror.a
    - pkg-config --print-errors --exact-version "20260107" absl_strerror
    - test -f $PREFIX/lib/libabsl_strings${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_strings.a
    - pkg-config --print-errors --exact-version "20260107" absl_strings
    - test -f $PREFIX/lib/libabsl_symbolize${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_symbolize.a
    - pkg-config --print-errors --exact-version "20260107" absl_symbolize
    - test -f $PREFIX/lib/libabsl_synchronization${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_synchronization.a
    - pkg-config --print-errors --exact-version "20260107" absl_synchronization
    - test -f $PREFIX/lib/libabsl_throw_delegate${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_throw_delegate.a
    - pkg-config --print-errors --exact-version "20260107" absl_throw_delegate
    - test -f $PREFIX/lib/libabsl_time${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_time.a
    - pkg-config --print-errors --exact-version "20260107" absl_time
    - test -f $PREFIX/lib/libabsl_time_zone${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_time_zone.a
    - pkg-config --print-errors --exact-version "20260107" absl_time_zone
    - test ! -f $PREFIX/lib/libabsl_scoped_mock_log${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libabsl_scoped_mock_log.a
    - cd cmake_test
    - export CMAKE_ARGS="$CMAKE_ARGS -GNinja -DCMAKE_BUILD_TYPE=Release"
    - cmake $CMAKE_ARGS  -DCMAKE_CXX_STANDARD=17 .
    - cmake --build .
    - ./flags_example
    - grep -q SHELL $PREFIX/lib/pkgconfig/absl_random_internal_randen_hwaes.pc &&
      exit 1 || exit 0
about:
  home: https://github.com/abseil/abseil-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Abseil Common Libraries (C++)
  description: 'Abseil is an open-source collection of C++ code (compliant to C++11)

    designed to augment the C++ standard library.

    '
  doc_url: https://github.com/abseil/abseil-cpp
  dev_url: https://github.com/abseil/abseil-cpp
extra:
  recipe-maintainers:
    - bluescarni
    - h-vetinari
    - njzjz
    - xhochy
  feedstock-name: abseil-cpp
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260211.2.1
  remote_url: https://github.com/conda-forge/abseil-cpp-feedstock
  sha: bada3e17e619994bcf9ceaa59c00ef20bb12cd74
