# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Thu Jul 31 07:47:39 2025
# ------------------------------------------------

package:
  name: libuv
  version: 1.51.0
source:
  url: https://github.com/libuv/libuv/archive/v1.51.0.tar.gz
  sha256: 27e55cf7083913bfb6826ca78cde9de7647cded648d35f24163f2d31bb9f51cd
  patches:
    - boottime.patch
build:
  number: '1'
  run_exports:
    - libuv >=1.51.0,<2.0a0
  string: h6caf38d_1
requirements:
  build:
    - autoconf 2.72 pl5321had7229c_1
    - automake 1.17 pl5321h694c41f_0
    - ca-certificates 2025.7.14 hbd8a1cb_0
    - cctools_osx-64 1021.4 haa85c18_1
    - cctools_osx-arm64 1021.4 h65996a6_1
    - clang 19.1.7 default_h576c50e_3
    - clang-19 19.1.7 default_h3571c67_3
    - clang_impl_osx-arm64 19.1.7 h4fa02b8_25
    - clang_osx-arm64 19.1.7 h1728699_25
    - compiler-rt 19.1.7 h52031e2_0
    - compiler-rt_osx-64 19.1.7 hc6f8467_0
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 954.16 hf1c22e8_1
    - ld64_osx-arm64 954.16 h59013cd_1
    - libclang-cpp19.1 19.1.7 default_h3571c67_3
    - libcxx 20.1.8 h3d58e20_1
    - libiconv 1.18 h4b5e92a_1
    - libintl 0.25.1 h3184127_1
    - libllvm19 19.1.7 hc29ff6c_1
    - libltdl 2.4.3a h240833e_0
    - liblzma 5.8.1 hd471939_2
    - libtool 2.5.4 h240833e_0
    - libxml2 2.13.8 h93c44a6_0
    - libzlib 1.3.1 hd23fc13_2
    - llvm-tools 19.1.7 h3fe3016_1
    - llvm-tools-19 19.1.7 he90a8e3_1
    - m4 1.4.20 h6e16a3a_0
    - macosx_deployment_target_osx-arm64 11.0 h6553868_2
    - make 4.4.1 h00291cd_2
    - ncurses 6.5 h0622a9a_3
    - openssl 3.5.1 hc426f3f_0
    - perl 5.32.1 7_h10d778d_perl5
    - sed 4.9 hf9b2955_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1300.6.5 h390ca13_0
    - zstd 1.5.7 h8210216_2
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
test:
  commands:
    - test -f "$PREFIX/include/uv.h"
    - test -f "$PREFIX/lib/libuv.a"
    - test -f "$PREFIX/lib/libuv.1.dylib"
    - test -f "$PREFIX/lib/libuv${SHLIB_EXT}"
    - test -f "$PREFIX/lib/pkgconfig/libuv.pc"
about:
  home: http://libuv.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Cross-platform asynchronous I/O
  description: 'libuv is a multi-platform support library with a focus on asynchronous
    I/O.

    It was primarily developed for use by Node.js, but it''s also used by Luvit,

    Julia, pyuv, and others.

    '
  doc_url: http://docs.libuv.org/
  dev_url: https://github.com/libuv/libuv
extra:
  recipe-maintainers:
    - frol
    - jjerphan
    - mariusvniekerk
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250731.1.1
  remote_url: https://github.com/conda-forge/libuv-feedstock
  sha: 5e6db13623701056d1916d207960a024bf98c88b
