# This file created by conda-build 25.11.1
# ------------------------------------------------

package:
  name: openssl
  version: 3.6.1
source:
  url: https://github.com/openssl/openssl/releases/download/openssl-3.6.1/openssl-3.6.1.tar.gz
  sha256: b1bfedcd5b289ff22aee87c9d600f515767ebf45f77168cb6d64f231f518a82e
build:
  run_exports:
    - openssl >=3.6.1,<4.0a0
  number: 1
  string: hd24854e_1
requirements:
  build:
    - clang_bootstrap_osx-arm64 19.1.7 h4c5f930_31
    - macosx_deployment_target_osx-arm64 11.0 h214bdd9_6
    - make 4.4.1 h00291cd_2
    - perl 5.32.1 7_h10d778d_perl5
  run:
    - __osx >=11.0
    - ca-certificates
  host:
    - __osx >=11.0
test:
  requires:
    - pkg-config
    - ripgrep
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.6.1" openssl
    - if [[ "$(pkg-config --variable=prefix openssl)" == "" ]]; then exit 1; fi
about:
  home: https://www.openssl.org/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://docs.openssl.org/master/
extra:
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  feedstock-name: openssl
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260127.15.1
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: 3d85e0e6e215fda75bf75557b62878c9b7c54eea
